-- 코드를 작성해주세요
SELECT
CASE
WHEN MONTH(DIFFERENTIATION_DATE) >= 1 and MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
WHEN MONTH(DIFFERENTIATION_DATE) >= 4 and MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
WHEN MONTH(DIFFERENTIATION_DATE) >= 7 and MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
WHEN MONTH(DIFFERENTIATION_DATE) >= 10 and MONTH(DIFFERENTIATION_DATE) <= 12 THEN '4Q'
END
AS QUARTER,
COUNT(ID) as ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER asc;