-- 코드를 작성해주세요
SELECT 
YEAR(DIFFERENTIATION_DATE) as YEAR, 
B.MAX_SIZE - A.SIZE_OF_COLONY as YEAR_DEV, 
ID
FROM 
ECOLI_DATA as A
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, 
    MAX(SIZE_OF_COLONY) as MAX_SIZE
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)) 
    as B
ON YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;
